apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: stripe_oltp
    user: stripe_user
    secureJsonData:
      password: stripe_password
    jsonData:
      sslmode: 'disable'
      postgresVersion: 1500
    editable: true

  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    url: http://clickhouse:8123
    database: stripe_olap
    basicAuth: true
    basicAuthUser: stripe_user
    secureJsonData:
      basicAuthPassword: stripe_password
    editable: true
