name: Automatic deployment to huggingface_hub

on:
  push:
    branches:
      - master

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # ← Récupère tout l'historique Git

      - name: Tag validated version
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag "pushed-v${{ github.run_number }}"
          git push origin "pushed-v${{ github.run_number }}"

  deploy:
    needs: tag # ← Deploy APRÈS le tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install huggingface_hub

      - name: Deploy to Hugging Face Spaces
        run: |
          python -c "
          from huggingface_hub import HfApi
          api = HfApi(token='${{ secrets.HF_TOKEN }}')
          api.upload_folder(
              folder_path='./Bloc4 - Final project/Projet/Architecture/App/Dockers/streamlit',
              repo_id='DavidRambeau/bloc3_Streamlit',
              repo_type='space'
          )
          "
